//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGST.Bill_Svc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Bill_Svc.IBillService")]
    public interface IBillService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/GetList_Bill", ReplyAction="http://tempuri.org/IBillService/GetList_BillResponse")]
        System.Collections.Generic.List<BusinessObjects.InvoiceInfo> GetList_Bill(string InvoiceID, string BranchID, string CusID, string OrganizationCode, string InvoiceDateFrom, string InvoiceDateTo, string IsReturned, string IsCancelled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/GetList_Bill", ReplyAction="http://tempuri.org/IBillService/GetList_BillResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.InvoiceInfo>> GetList_BillAsync(string InvoiceID, string BranchID, string CusID, string OrganizationCode, string InvoiceDateFrom, string InvoiceDateTo, string IsReturned, string IsCancelled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/GetDetails_Bill", ReplyAction="http://tempuri.org/IBillService/GetDetails_BillResponse")]
        BusinessObjects.InvoiceInfo GetDetails_Bill(string InvoiceID, string BranchID, string CusID, string OrganizationCode, string InvoiceDateFrom, string InvoiceDateTo, string IsReturned, string IsCancelled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/GetDetails_Bill", ReplyAction="http://tempuri.org/IBillService/GetDetails_BillResponse")]
        System.Threading.Tasks.Task<BusinessObjects.InvoiceInfo> GetDetails_BillAsync(string InvoiceID, string BranchID, string CusID, string OrganizationCode, string InvoiceDateFrom, string InvoiceDateTo, string IsReturned, string IsCancelled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/Save_Bill", ReplyAction="http://tempuri.org/IBillService/Save_BillResponse")]
        iGST.Bill_Svc.Save_BillResponse Save_Bill(iGST.Bill_Svc.Save_BillRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/Save_Bill", ReplyAction="http://tempuri.org/IBillService/Save_BillResponse")]
        System.Threading.Tasks.Task<iGST.Bill_Svc.Save_BillResponse> Save_BillAsync(iGST.Bill_Svc.Save_BillRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/GetList_Customer", ReplyAction="http://tempuri.org/IBillService/GetList_CustomerResponse")]
        System.Collections.Generic.List<BusinessObjects.CustomerInfo> GetList_Customer(string UserType, string CusID, string BranchId, string OrganizationCode, bool IsActive, string UserID, string LanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/GetList_Customer", ReplyAction="http://tempuri.org/IBillService/GetList_CustomerResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.CustomerInfo>> GetList_CustomerAsync(string UserType, string CusID, string BranchId, string OrganizationCode, bool IsActive, string UserID, string LanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/GetDetails_Customer", ReplyAction="http://tempuri.org/IBillService/GetDetails_CustomerResponse")]
        BusinessObjects.CustomerInfo GetDetails_Customer(string UserType, string CusID, string BranchId, string OrganizationCode, bool IsActive, string UserID, string LanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/GetDetails_Customer", ReplyAction="http://tempuri.org/IBillService/GetDetails_CustomerResponse")]
        System.Threading.Tasks.Task<BusinessObjects.CustomerInfo> GetDetails_CustomerAsync(string UserType, string CusID, string BranchId, string OrganizationCode, bool IsActive, string UserID, string LanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/Upload_Customer", ReplyAction="http://tempuri.org/IBillService/Upload_CustomerResponse")]
        iGST.Bill_Svc.Upload_CustomerResponse Upload_Customer(iGST.Bill_Svc.Upload_CustomerRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/Upload_Customer", ReplyAction="http://tempuri.org/IBillService/Upload_CustomerResponse")]
        System.Threading.Tasks.Task<iGST.Bill_Svc.Upload_CustomerResponse> Upload_CustomerAsync(iGST.Bill_Svc.Upload_CustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/Save_Customer", ReplyAction="http://tempuri.org/IBillService/Save_CustomerResponse")]
        iGST.Bill_Svc.Save_CustomerResponse Save_Customer(iGST.Bill_Svc.Save_CustomerRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/Save_Customer", ReplyAction="http://tempuri.org/IBillService/Save_CustomerResponse")]
        System.Threading.Tasks.Task<iGST.Bill_Svc.Save_CustomerResponse> Save_CustomerAsync(iGST.Bill_Svc.Save_CustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/Save_CustomerImage", ReplyAction="http://tempuri.org/IBillService/Save_CustomerImageResponse")]
        iGST.Bill_Svc.Save_CustomerImageResponse Save_CustomerImage(iGST.Bill_Svc.Save_CustomerImageRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/Save_CustomerImage", ReplyAction="http://tempuri.org/IBillService/Save_CustomerImageResponse")]
        System.Threading.Tasks.Task<iGST.Bill_Svc.Save_CustomerImageResponse> Save_CustomerImageAsync(iGST.Bill_Svc.Save_CustomerImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/GetList_CustomerImage", ReplyAction="http://tempuri.org/IBillService/GetList_CustomerImageResponse")]
        System.Collections.Generic.List<BusinessObjects.CustomerImageInfo> GetList_CustomerImage(string ImageId, string CustomerID, string IsActive, string IsMain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/GetList_CustomerImage", ReplyAction="http://tempuri.org/IBillService/GetList_CustomerImageResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.CustomerImageInfo>> GetList_CustomerImageAsync(string ImageId, string CustomerID, string IsActive, string IsMain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/GetDetails_CustomerImage", ReplyAction="http://tempuri.org/IBillService/GetDetails_CustomerImageResponse")]
        BusinessObjects.CustomerImageInfo GetDetails_CustomerImage(string ImageId, string CustomerID, string IsActive, string IsMain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/GetDetails_CustomerImage", ReplyAction="http://tempuri.org/IBillService/GetDetails_CustomerImageResponse")]
        System.Threading.Tasks.Task<BusinessObjects.CustomerImageInfo> GetDetails_CustomerImageAsync(string ImageId, string CustomerID, string IsActive, string IsMain);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save_Bill", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Save_BillRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool isOnlyDelete;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public BusinessObjects.InvoiceInfo objBillInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string UserCode;
        
        public Save_BillRequest() {
        }
        
        public Save_BillRequest(bool isOnlyDelete, BusinessObjects.InvoiceInfo objBillInfo, string UserCode) {
            this.isOnlyDelete = isOnlyDelete;
            this.objBillInfo = objBillInfo;
            this.UserCode = UserCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save_BillResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Save_BillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Save_BillResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errormsg;
        
        public Save_BillResponse() {
        }
        
        public Save_BillResponse(bool Save_BillResult, string errormsg) {
            this.Save_BillResult = Save_BillResult;
            this.errormsg = errormsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Upload_Customer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Upload_CustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool isOvereWrite;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Data.DataSet ds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string OrganizationCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string UserCode;
        
        public Upload_CustomerRequest() {
        }
        
        public Upload_CustomerRequest(string UserType, bool isOvereWrite, System.Data.DataSet ds, string OrganizationCode, string UserCode) {
            this.UserType = UserType;
            this.isOvereWrite = isOvereWrite;
            this.ds = ds;
            this.OrganizationCode = OrganizationCode;
            this.UserCode = UserCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Upload_CustomerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Upload_CustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet Upload_CustomerResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool bReturn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string errormsg;
        
        public Upload_CustomerResponse() {
        }
        
        public Upload_CustomerResponse(System.Data.DataSet Upload_CustomerResult, bool bReturn, string errormsg) {
            this.Upload_CustomerResult = Upload_CustomerResult;
            this.bReturn = bReturn;
            this.errormsg = errormsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save_Customer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Save_CustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool isOnlyDelete;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public BusinessObjects.CustomerInfo objCustomerInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string UserCode;
        
        public Save_CustomerRequest() {
        }
        
        public Save_CustomerRequest(string UserType, bool isOnlyDelete, BusinessObjects.CustomerInfo objCustomerInfo, string UserCode) {
            this.UserType = UserType;
            this.isOnlyDelete = isOnlyDelete;
            this.objCustomerInfo = objCustomerInfo;
            this.UserCode = UserCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save_CustomerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Save_CustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Save_CustomerResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errormsg;
        
        public Save_CustomerResponse() {
        }
        
        public Save_CustomerResponse(bool Save_CustomerResult, string errormsg) {
            this.Save_CustomerResult = Save_CustomerResult;
            this.errormsg = errormsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save_CustomerImage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Save_CustomerImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool isOnlyDelete;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public BusinessObjects.CustomerImageInfo obj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string UserCode;
        
        public Save_CustomerImageRequest() {
        }
        
        public Save_CustomerImageRequest(bool isOnlyDelete, BusinessObjects.CustomerImageInfo obj, string UserCode) {
            this.isOnlyDelete = isOnlyDelete;
            this.obj = obj;
            this.UserCode = UserCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save_CustomerImageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Save_CustomerImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Save_CustomerImageResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errormsg;
        
        public Save_CustomerImageResponse() {
        }
        
        public Save_CustomerImageResponse(bool Save_CustomerImageResult, string errormsg) {
            this.Save_CustomerImageResult = Save_CustomerImageResult;
            this.errormsg = errormsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBillServiceChannel : iGST.Bill_Svc.IBillService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BillServiceClient : System.ServiceModel.ClientBase<iGST.Bill_Svc.IBillService>, iGST.Bill_Svc.IBillService {
        
        public BillServiceClient() {
        }
        
        public BillServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BillServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<BusinessObjects.InvoiceInfo> GetList_Bill(string InvoiceID, string BranchID, string CusID, string OrganizationCode, string InvoiceDateFrom, string InvoiceDateTo, string IsReturned, string IsCancelled) {
            return base.Channel.GetList_Bill(InvoiceID, BranchID, CusID, OrganizationCode, InvoiceDateFrom, InvoiceDateTo, IsReturned, IsCancelled);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.InvoiceInfo>> GetList_BillAsync(string InvoiceID, string BranchID, string CusID, string OrganizationCode, string InvoiceDateFrom, string InvoiceDateTo, string IsReturned, string IsCancelled) {
            return base.Channel.GetList_BillAsync(InvoiceID, BranchID, CusID, OrganizationCode, InvoiceDateFrom, InvoiceDateTo, IsReturned, IsCancelled);
        }
        
        public BusinessObjects.InvoiceInfo GetDetails_Bill(string InvoiceID, string BranchID, string CusID, string OrganizationCode, string InvoiceDateFrom, string InvoiceDateTo, string IsReturned, string IsCancelled) {
            return base.Channel.GetDetails_Bill(InvoiceID, BranchID, CusID, OrganizationCode, InvoiceDateFrom, InvoiceDateTo, IsReturned, IsCancelled);
        }
        
        public System.Threading.Tasks.Task<BusinessObjects.InvoiceInfo> GetDetails_BillAsync(string InvoiceID, string BranchID, string CusID, string OrganizationCode, string InvoiceDateFrom, string InvoiceDateTo, string IsReturned, string IsCancelled) {
            return base.Channel.GetDetails_BillAsync(InvoiceID, BranchID, CusID, OrganizationCode, InvoiceDateFrom, InvoiceDateTo, IsReturned, IsCancelled);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iGST.Bill_Svc.Save_BillResponse iGST.Bill_Svc.IBillService.Save_Bill(iGST.Bill_Svc.Save_BillRequest request) {
            return base.Channel.Save_Bill(request);
        }
        
        public bool Save_Bill(bool isOnlyDelete, BusinessObjects.InvoiceInfo objBillInfo, string UserCode, out string errormsg) {
            iGST.Bill_Svc.Save_BillRequest inValue = new iGST.Bill_Svc.Save_BillRequest();
            inValue.isOnlyDelete = isOnlyDelete;
            inValue.objBillInfo = objBillInfo;
            inValue.UserCode = UserCode;
            iGST.Bill_Svc.Save_BillResponse retVal = ((iGST.Bill_Svc.IBillService)(this)).Save_Bill(inValue);
            errormsg = retVal.errormsg;
            return retVal.Save_BillResult;
        }
        
        public System.Threading.Tasks.Task<iGST.Bill_Svc.Save_BillResponse> Save_BillAsync(iGST.Bill_Svc.Save_BillRequest request) {
            return base.Channel.Save_BillAsync(request);
        }
        
        public System.Collections.Generic.List<BusinessObjects.CustomerInfo> GetList_Customer(string UserType, string CusID, string BranchId, string OrganizationCode, bool IsActive, string UserID, string LanguageId) {
            return base.Channel.GetList_Customer(UserType, CusID, BranchId, OrganizationCode, IsActive, UserID, LanguageId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.CustomerInfo>> GetList_CustomerAsync(string UserType, string CusID, string BranchId, string OrganizationCode, bool IsActive, string UserID, string LanguageId) {
            return base.Channel.GetList_CustomerAsync(UserType, CusID, BranchId, OrganizationCode, IsActive, UserID, LanguageId);
        }
        
        public BusinessObjects.CustomerInfo GetDetails_Customer(string UserType, string CusID, string BranchId, string OrganizationCode, bool IsActive, string UserID, string LanguageId) {
            return base.Channel.GetDetails_Customer(UserType, CusID, BranchId, OrganizationCode, IsActive, UserID, LanguageId);
        }
        
        public System.Threading.Tasks.Task<BusinessObjects.CustomerInfo> GetDetails_CustomerAsync(string UserType, string CusID, string BranchId, string OrganizationCode, bool IsActive, string UserID, string LanguageId) {
            return base.Channel.GetDetails_CustomerAsync(UserType, CusID, BranchId, OrganizationCode, IsActive, UserID, LanguageId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iGST.Bill_Svc.Upload_CustomerResponse iGST.Bill_Svc.IBillService.Upload_Customer(iGST.Bill_Svc.Upload_CustomerRequest request) {
            return base.Channel.Upload_Customer(request);
        }
        
        public System.Data.DataSet Upload_Customer(string UserType, bool isOvereWrite, System.Data.DataSet ds, string OrganizationCode, string UserCode, out bool bReturn, out string errormsg) {
            iGST.Bill_Svc.Upload_CustomerRequest inValue = new iGST.Bill_Svc.Upload_CustomerRequest();
            inValue.UserType = UserType;
            inValue.isOvereWrite = isOvereWrite;
            inValue.ds = ds;
            inValue.OrganizationCode = OrganizationCode;
            inValue.UserCode = UserCode;
            iGST.Bill_Svc.Upload_CustomerResponse retVal = ((iGST.Bill_Svc.IBillService)(this)).Upload_Customer(inValue);
            bReturn = retVal.bReturn;
            errormsg = retVal.errormsg;
            return retVal.Upload_CustomerResult;
        }
        
        public System.Threading.Tasks.Task<iGST.Bill_Svc.Upload_CustomerResponse> Upload_CustomerAsync(iGST.Bill_Svc.Upload_CustomerRequest request) {
            return base.Channel.Upload_CustomerAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iGST.Bill_Svc.Save_CustomerResponse iGST.Bill_Svc.IBillService.Save_Customer(iGST.Bill_Svc.Save_CustomerRequest request) {
            return base.Channel.Save_Customer(request);
        }
        
        public bool Save_Customer(string UserType, bool isOnlyDelete, BusinessObjects.CustomerInfo objCustomerInfo, string UserCode, out string errormsg) {
            iGST.Bill_Svc.Save_CustomerRequest inValue = new iGST.Bill_Svc.Save_CustomerRequest();
            inValue.UserType = UserType;
            inValue.isOnlyDelete = isOnlyDelete;
            inValue.objCustomerInfo = objCustomerInfo;
            inValue.UserCode = UserCode;
            iGST.Bill_Svc.Save_CustomerResponse retVal = ((iGST.Bill_Svc.IBillService)(this)).Save_Customer(inValue);
            errormsg = retVal.errormsg;
            return retVal.Save_CustomerResult;
        }
        
        public System.Threading.Tasks.Task<iGST.Bill_Svc.Save_CustomerResponse> Save_CustomerAsync(iGST.Bill_Svc.Save_CustomerRequest request) {
            return base.Channel.Save_CustomerAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iGST.Bill_Svc.Save_CustomerImageResponse iGST.Bill_Svc.IBillService.Save_CustomerImage(iGST.Bill_Svc.Save_CustomerImageRequest request) {
            return base.Channel.Save_CustomerImage(request);
        }
        
        public bool Save_CustomerImage(bool isOnlyDelete, BusinessObjects.CustomerImageInfo obj, string UserCode, out string errormsg) {
            iGST.Bill_Svc.Save_CustomerImageRequest inValue = new iGST.Bill_Svc.Save_CustomerImageRequest();
            inValue.isOnlyDelete = isOnlyDelete;
            inValue.obj = obj;
            inValue.UserCode = UserCode;
            iGST.Bill_Svc.Save_CustomerImageResponse retVal = ((iGST.Bill_Svc.IBillService)(this)).Save_CustomerImage(inValue);
            errormsg = retVal.errormsg;
            return retVal.Save_CustomerImageResult;
        }
        
        public System.Threading.Tasks.Task<iGST.Bill_Svc.Save_CustomerImageResponse> Save_CustomerImageAsync(iGST.Bill_Svc.Save_CustomerImageRequest request) {
            return base.Channel.Save_CustomerImageAsync(request);
        }
        
        public System.Collections.Generic.List<BusinessObjects.CustomerImageInfo> GetList_CustomerImage(string ImageId, string CustomerID, string IsActive, string IsMain) {
            return base.Channel.GetList_CustomerImage(ImageId, CustomerID, IsActive, IsMain);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.CustomerImageInfo>> GetList_CustomerImageAsync(string ImageId, string CustomerID, string IsActive, string IsMain) {
            return base.Channel.GetList_CustomerImageAsync(ImageId, CustomerID, IsActive, IsMain);
        }
        
        public BusinessObjects.CustomerImageInfo GetDetails_CustomerImage(string ImageId, string CustomerID, string IsActive, string IsMain) {
            return base.Channel.GetDetails_CustomerImage(ImageId, CustomerID, IsActive, IsMain);
        }
        
        public System.Threading.Tasks.Task<BusinessObjects.CustomerImageInfo> GetDetails_CustomerImageAsync(string ImageId, string CustomerID, string IsActive, string IsMain) {
            return base.Channel.GetDetails_CustomerImageAsync(ImageId, CustomerID, IsActive, IsMain);
        }
    }
}
