using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BusinessObjects
{
    [Serializable]
    public class UserEmailInfo
    {
        public string UserID { get; set; }
        public string EmailID { get; set; }
        public bool IsEmailConfirmationSend { get; set; }
        public string EmailConfirmationSentOn { get; set; }
        public bool IsEmailVerified { get; set; }
        public string EmailVerifiedOn { get; set; }
        public string LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public string ActivityType { get; set; }
        public bool IsActive { get; set; }
        public string DatauniqueID { get; set; }
    }

    [Serializable]
    public class UserInfo
    {
        public UserInfo()
        {
            this.UserID = "";
            this.UserType = "";
            this.UserCode = "";
            this.OrganizationCode = "";
        }

        public string UserType { get; set; }
        public string UserID { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public string Title { get; set; }
        public string Safix { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string DisplayName { get; set; }
        public string DOB { get; set; }
        public string Sex { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string CityName { get; set; }
        public string StateName { get; set; }
        public string CountryName { get; set; }
        public string PIN { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public bool AccessAllowed { get; set; }
        public bool IsApproved { get; set; }
        public bool IsMainUser { get; set; }
        public string ActivityType { get; set; }
        public bool IsActive { get; set; }
        public string DatauniqueID { get; set; }
        public string OrganizationCode { get; set; }
        public string OrganizationName { get; set; }
        //public List<BranchProductMappingInfo> ProductList { get { return _ProductList; } set { _ProductList = value; }}
        public List<UserBranchRoleMappingInfo> UserRoleList { get; set; }
        public UserMobileInfo UserRegisteredMobile { get; set; }
        public UserEmailInfo UserRegisteredEmail { get; set; }

        public string BillingRatePerHour { get; set; }
        public bool isBillableBydefault { get; set; }
        public string EmployeeID { get; set; }
        public string HireDate { get; set; }
        public string ReleaseDate { get; set; }
        public string ManagerName { get; set; }
        public string ManagerID { get; set; }
        public string Notes { get; set; }
        public string MobileNumber { get; set; }
        public string EmailID { get; set; }
        public bool IsMobileActive { get; set; }
        public bool IsEmailActive { get; set; }
        public string Password { get; set; }
        public string SsseionID { get; set; }
        public RoleInfo EffectiveRole { get; set; }
        public string Functions { get; set; }
        public string UserTypeName { get; set; }
        public List<UserBranchRoleMappingInfo> UserBranchRoleList { get; set; }
        public List<CurrencyOrganiztionInfo> ApplicableCurrencies { get; set; }
    }

    [Serializable]
    public class UserMobileInfo
    {
        public string UserID { get; set; }
        public string Mobile { get; set; }
        public bool IsMobileConfirmationSent { get; set; }
        public string MobileConfirmationSentOn { get; set; }
        public bool IsMobileVerified { get; set; }
        public string MobileVerifiedOn { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public string ActivityType { get; set; }
        public bool IsActive { get; set; }
        public string DatauniqueID { get; set; }
    }

    [Serializable]
    public class UserPasswordInfo
    {
        public string UserID { get; set; }
        public string Password { get; set; }
        public string IsAutoGenerated { get; set; }
        public string AutoGeneratedOn { get; set; }
        public string AutoGeneratedValidityTill { get; set; }
        public string AutoGeneratedSubmittedOn { get; set; }
        public int NumberOfWrongPassword { get; set; }
        public string IsPasswordLocked { get; set; }
        public string PasswordValidTill { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
    }

    [Serializable]
    public class UserBranchRoleMappingInfo
    {
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public string FunctionID { get; set; }
        public string FunctionName { get; set; }
        public string OrganizationCode { get; set; }
        public string OrganizationName { get; set; }
        public string BranchID { get; set; }
        public string BranchName { get; set; }
        public string DataUniqueID { get; set; }
        public bool isSelected { get; set; }

    }

    [Serializable]
    public class FaceBookUser
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string PictureUrl { get; set; }
        public string Email { get; set; }
    }


    /*
     public class UserInfo
    {
        public bool _accessallowed = false;
        public string _UserType = "";
        public string _UserID = "";
        public string _UserCode = "";
        public string _UserName = "";
        public string _Title = "";
        public string _First_Name = "";
        public string _Middle_Name = "";
        public string _Last_Name = "";
        public string _DOB = "";
        public string _Sex = "";
        public string _Street1 = "";
        public string _Street2 = "";
        public string _City = "";
        public string _State = "";
        public string _Country = "";
        public string _CityName = "";
        public string _StateName = "";
        public string _CountryName = "";
        public string _PIN = "";
        public System.DateTime _LastModifiedOn;
        public string _LastModifiedBy = "";
        public bool _AccessAllowed = false;
        public bool _IsApproved = false;
        public bool _IsMainUser = false;
        public string _ActivityType = "";
        public bool _IsActive = false;
        public string _DatauniqueID = "";
        public string _OrganizationCode = "";
        public string _OrganizationName = "";
        //public List<BranchProductMappingInfo> _ProductList = null;
        public List<UserBranchRoleMappingInfo> _UserRoleList = null;
        public UserMobileInfo _UserRegisteredMobile = null;
        public UserEmailInfo _UserRegisteredEmail = null;

        public string _BillingRatePerHour = "";
        public bool _isBillableBydefault = false;
        public string _EmployeeID = "";
        public string _HireDate = "";
        public string _ReleaseDate = "";
        public string _ManagerName = "";
        public string _ManagerID = "";
        public string _Notes = "";
        public string _MobileNumber = "";
        public string _EmailID = "";
        public bool _IsMobileActive = false;
        public bool _IsEmailActive = false;
        public string _Password = "";
        public string _SsseionID = "";
        public RoleInfo _EffectiveRole = null;
        public string _Functions = "";
        public string _UserTypeName = "";
        public List<UserBranchRoleMappingInfo> _UserBranchRoleList = null;
        public UserInfo()
        {
            this.UserID = "";
            this.UserType = "";
            this.UserCode = "";
            this.OrganizationCode = "";
        }

        public string UserType { get { return _UserType; } set { _UserType = value; }}
        public string UserID { get { return _UserID; } set { _UserID = value; }}
        public string UserCode { get { return _UserCode; } set { _UserCode = value; }}
        public string UserName { get { return _UserName; } set { _UserName = value; }}
        public string Title { get { return _Title; } set { _Title = value; }}
        public string First_Name { get { return _First_Name; } set { _First_Name = value; }}
        public string Middle_Name { get { return _Middle_Name; } set { _Middle_Name = value; }}
        public string Last_Name { get { return _Last_Name; } set { _Last_Name = value; }}
        public string DOB { get { return _DOB; } set { _DOB = value; }}
        public string Sex { get { return _Sex; } set { _Sex = value; }}
        public string Street1 { get { return _Street1; } set { _Street1 = value; }}
        public string Street2 { get { return _Street2; } set { _Street2= value; }}
        public string City { get { return _City; } set { _City = value; }}
        public string State { get { return _State; } set { _State = value; }}
        public string Country { get { return _Country; } set { _Country = value; }}
        public string CityName { get { return _CityName; } set { _CityName = value; }}
        public string StateName { get { return _StateName; } set { _StateName = value; }}
        public string CountryName { get { return _CountryName; } set { _CountryName = value; }}
        public string PIN { get { return _PIN; } set { _PIN = value; }}
        public System.DateTime LastModifiedOn { get { return _LastModifiedOn; } set { _LastModifiedOn = value; }}
        public string LastModifiedBy { get { return _LastModifiedBy; } set { _LastModifiedBy = value; }}
        public bool AccessAllowed { get { return _accessallowed; } set { _accessallowed = value; } }
        public bool IsApproved { get { return _accessallowed; } set { _accessallowed = value; }}
        public bool IsMainUser { get { return _IsMainUser; } set { _IsMainUser = value; }}
        public string ActivityType { get { return _ActivityType; } set { _ActivityType = value; }}
        public bool IsActive { get { return _IsActive; } set { _IsActive = value; }}
        public string DatauniqueID { get { return _DatauniqueID; } set { _DatauniqueID = value; }}
        public string OrganizationCode { get { return _OrganizationCode; } set { _OrganizationCode = value; }}
        public string OrganizationName { get { return _OrganizationName; } set { _OrganizationName = value; }}
        //public List<BranchProductMappingInfo> ProductList { get { return _ProductList; } set { _ProductList = value; }}
        public List<UserBranchRoleMappingInfo> UserRoleList { get { return _UserRoleList; } set { _UserRoleList = value; }}
        public UserMobileInfo UserRegisteredMobile { get { return _UserRegisteredMobile; } set { _UserRegisteredMobile = value; }}
        public UserEmailInfo UserRegisteredEmail { get { return _UserRegisteredEmail; } set { _UserRegisteredEmail = value; }}

        public string BillingRatePerHour { get { return _BillingRatePerHour; } set { _BillingRatePerHour = value; }}
        public bool isBillableBydefault { get { return _isBillableBydefault; } set { _isBillableBydefault = value; }}
        public string EmployeeID { get { return _EmployeeID; } set { _EmployeeID = value; }}
        public string HireDate { get { return _HireDate; } set { _HireDate = value; }}
        public string ReleaseDate { get { return _ReleaseDate; } set { _ReleaseDate = value; }}
        public string ManagerName { get { return _ManagerName; } set { _ManagerName = value; }}
        public string ManagerID { get { return _ManagerID; } set { _ManagerID = value; }}
        public string Notes { get { return _Notes; } set { _Notes = value; }}
        public string MobileNumber { get { return _MobileNumber; } set { _MobileNumber = value; }}
        public string EmailID { get { return _EmailID; } set { _EmailID = value; }}
        public bool IsMobileActive { get { return _IsMobileActive; } set {_IsMobileActive= value; }}
        public bool IsEmailActive { get { return _IsEmailActive; } set { _IsEmailActive = value; }}
        public string Password { get { return _Password; } set { _Password= value; }}
        public string SsseionID { get { return _SsseionID; } set { _SsseionID = value; }}
        public RoleInfo EffectiveRole { get { return _EffectiveRole; } set { _EffectiveRole = value; }}
        public string Functions { get { return _Functions; } set { _Functions = value; }}
        public string UserTypeName { get { return _UserTypeName; } set { _UserTypeName = value; }}
        public List<UserBranchRoleMappingInfo> UserBranchRoleList { get { return _UserBranchRoleList; } set { _UserBranchRoleList = value; }}
    }
     */
}
