//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGST.Auth_Svc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Auth_Svc.IUserAuthenticationService")]
    public interface IUserAuthenticationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/User_Login", ReplyAction="http://tempuri.org/IUserAuthenticationService/User_LoginResponse")]
        iGST.Auth_Svc.User_LoginResponse User_Login(iGST.Auth_Svc.User_LoginRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/User_Login", ReplyAction="http://tempuri.org/IUserAuthenticationService/User_LoginResponse")]
        System.Threading.Tasks.Task<iGST.Auth_Svc.User_LoginResponse> User_LoginAsync(iGST.Auth_Svc.User_LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/User_ChangePassword", ReplyAction="http://tempuri.org/IUserAuthenticationService/User_ChangePasswordResponse")]
        iGST.Auth_Svc.User_ChangePasswordResponse User_ChangePassword(iGST.Auth_Svc.User_ChangePasswordRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/User_ChangePassword", ReplyAction="http://tempuri.org/IUserAuthenticationService/User_ChangePasswordResponse")]
        System.Threading.Tasks.Task<iGST.Auth_Svc.User_ChangePasswordResponse> User_ChangePasswordAsync(iGST.Auth_Svc.User_ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/User_ForgotPassword", ReplyAction="http://tempuri.org/IUserAuthenticationService/User_ForgotPasswordResponse")]
        iGST.Auth_Svc.User_ForgotPasswordResponse User_ForgotPassword(iGST.Auth_Svc.User_ForgotPasswordRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/User_ForgotPassword", ReplyAction="http://tempuri.org/IUserAuthenticationService/User_ForgotPasswordResponse")]
        System.Threading.Tasks.Task<iGST.Auth_Svc.User_ForgotPasswordResponse> User_ForgotPasswordAsync(iGST.Auth_Svc.User_ForgotPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/SocialMediaLogin", ReplyAction="http://tempuri.org/IUserAuthenticationService/SocialMediaLoginResponse")]
        iGST.Auth_Svc.SocialMediaLoginResponse SocialMediaLogin(iGST.Auth_Svc.SocialMediaLoginRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/SocialMediaLogin", ReplyAction="http://tempuri.org/IUserAuthenticationService/SocialMediaLoginResponse")]
        System.Threading.Tasks.Task<iGST.Auth_Svc.SocialMediaLoginResponse> SocialMediaLoginAsync(iGST.Auth_Svc.SocialMediaLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/GetList_UserModerate", ReplyAction="http://tempuri.org/IUserAuthenticationService/GetList_UserModerateResponse")]
        System.Collections.Generic.List<BusinessObjects.UserInfo> GetList_UserModerate(string OrganizationCode, string UserCode, string UserType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/GetList_UserModerate", ReplyAction="http://tempuri.org/IUserAuthenticationService/GetList_UserModerateResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.UserInfo>> GetList_UserModerateAsync(string OrganizationCode, string UserCode, string UserType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/GetDetails_UserModerate", ReplyAction="http://tempuri.org/IUserAuthenticationService/GetDetails_UserModerateResponse")]
        BusinessObjects.UserInfo GetDetails_UserModerate(string UserCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/GetDetails_UserModerate", ReplyAction="http://tempuri.org/IUserAuthenticationService/GetDetails_UserModerateResponse")]
        System.Threading.Tasks.Task<BusinessObjects.UserInfo> GetDetails_UserModerateAsync(string UserCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/Save_UserModerate", ReplyAction="http://tempuri.org/IUserAuthenticationService/Save_UserModerateResponse")]
        iGST.Auth_Svc.Save_UserModerateResponse Save_UserModerate(iGST.Auth_Svc.Save_UserModerateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/Save_UserModerate", ReplyAction="http://tempuri.org/IUserAuthenticationService/Save_UserModerateResponse")]
        System.Threading.Tasks.Task<iGST.Auth_Svc.Save_UserModerateResponse> Save_UserModerateAsync(iGST.Auth_Svc.Save_UserModerateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/Email_Verification", ReplyAction="http://tempuri.org/IUserAuthenticationService/Email_VerificationResponse")]
        iGST.Auth_Svc.Email_VerificationResponse Email_Verification(iGST.Auth_Svc.Email_VerificationRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/Email_Verification", ReplyAction="http://tempuri.org/IUserAuthenticationService/Email_VerificationResponse")]
        System.Threading.Tasks.Task<iGST.Auth_Svc.Email_VerificationResponse> Email_VerificationAsync(iGST.Auth_Svc.Email_VerificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/UserLogin", ReplyAction="http://tempuri.org/IUserAuthenticationService/UserLoginResponse")]
        iGST.Auth_Svc.UserLoginResponse UserLogin(iGST.Auth_Svc.UserLoginRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/UserLogin", ReplyAction="http://tempuri.org/IUserAuthenticationService/UserLoginResponse")]
        System.Threading.Tasks.Task<iGST.Auth_Svc.UserLoginResponse> UserLoginAsync(iGST.Auth_Svc.UserLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/UserRegistered_EmailChange", ReplyAction="http://tempuri.org/IUserAuthenticationService/UserRegistered_EmailChangeResponse")]
        iGST.Auth_Svc.UserRegistered_EmailChangeResponse UserRegistered_EmailChange(iGST.Auth_Svc.UserRegistered_EmailChangeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/UserRegistered_EmailChange", ReplyAction="http://tempuri.org/IUserAuthenticationService/UserRegistered_EmailChangeResponse")]
        System.Threading.Tasks.Task<iGST.Auth_Svc.UserRegistered_EmailChangeResponse> UserRegistered_EmailChangeAsync(iGST.Auth_Svc.UserRegistered_EmailChangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/UserRegistered_MobileChange", ReplyAction="http://tempuri.org/IUserAuthenticationService/UserRegistered_MobileChangeResponse" +
            "")]
        iGST.Auth_Svc.UserRegistered_MobileChangeResponse UserRegistered_MobileChange(iGST.Auth_Svc.UserRegistered_MobileChangeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/UserRegistered_MobileChange", ReplyAction="http://tempuri.org/IUserAuthenticationService/UserRegistered_MobileChangeResponse" +
            "")]
        System.Threading.Tasks.Task<iGST.Auth_Svc.UserRegistered_MobileChangeResponse> UserRegistered_MobileChangeAsync(iGST.Auth_Svc.UserRegistered_MobileChangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/GetList_OrganizationDropdownList", ReplyAction="http://tempuri.org/IUserAuthenticationService/GetList_OrganizationDropdownListRes" +
            "ponse")]
        System.Collections.Generic.List<BusinessObjects.OrganizationInfo> GetList_OrganizationDropdownList(string OrganizationCode, string isActive, string UserCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/GetList_OrganizationDropdownList", ReplyAction="http://tempuri.org/IUserAuthenticationService/GetList_OrganizationDropdownListRes" +
            "ponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.OrganizationInfo>> GetList_OrganizationDropdownListAsync(string OrganizationCode, string isActive, string UserCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/GetList_Organization", ReplyAction="http://tempuri.org/IUserAuthenticationService/GetList_OrganizationResponse")]
        System.Collections.Generic.List<BusinessObjects.OrganizationInfo> GetList_Organization(string OrganizationCode, string OrganizationName, string City, string State, string Country, string UserID, bool IsActive, string LanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/GetList_Organization", ReplyAction="http://tempuri.org/IUserAuthenticationService/GetList_OrganizationResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.OrganizationInfo>> GetList_OrganizationAsync(string OrganizationCode, string OrganizationName, string City, string State, string Country, string UserID, bool IsActive, string LanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/GetDetails_Organization", ReplyAction="http://tempuri.org/IUserAuthenticationService/GetDetails_OrganizationResponse")]
        BusinessObjects.OrganizationInfo GetDetails_Organization(string OrganizationCode, string OrganizationName, string City, string State, string Country, string UserID, bool IsActive, bool NeedBranchList, string LanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/GetDetails_Organization", ReplyAction="http://tempuri.org/IUserAuthenticationService/GetDetails_OrganizationResponse")]
        System.Threading.Tasks.Task<BusinessObjects.OrganizationInfo> GetDetails_OrganizationAsync(string OrganizationCode, string OrganizationName, string City, string State, string Country, string UserID, bool IsActive, bool NeedBranchList, string LanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/Save_Organization", ReplyAction="http://tempuri.org/IUserAuthenticationService/Save_OrganizationResponse")]
        iGST.Auth_Svc.Save_OrganizationResponse Save_Organization(iGST.Auth_Svc.Save_OrganizationRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/Save_Organization", ReplyAction="http://tempuri.org/IUserAuthenticationService/Save_OrganizationResponse")]
        System.Threading.Tasks.Task<iGST.Auth_Svc.Save_OrganizationResponse> Save_OrganizationAsync(iGST.Auth_Svc.Save_OrganizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/GetList_OrganizationAccountant", ReplyAction="http://tempuri.org/IUserAuthenticationService/GetList_OrganizationAccountantRespo" +
            "nse")]
        System.Collections.Generic.List<BusinessObjects.OrganizationAccountantInfo> GetList_OrganizationAccountant(string ID, string OrganizationCode, string AccountantCode, bool IsAudit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/GetList_OrganizationAccountant", ReplyAction="http://tempuri.org/IUserAuthenticationService/GetList_OrganizationAccountantRespo" +
            "nse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.OrganizationAccountantInfo>> GetList_OrganizationAccountantAsync(string ID, string OrganizationCode, string AccountantCode, bool IsAudit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/GetDetails_OrganizationAccountant", ReplyAction="http://tempuri.org/IUserAuthenticationService/GetDetails_OrganizationAccountantRe" +
            "sponse")]
        System.Collections.Generic.List<BusinessObjects.OrganizationAccountantInfo> GetDetails_OrganizationAccountant(string ID, string OrganizationCode, string AccountantCode, bool IsAudit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/GetDetails_OrganizationAccountant", ReplyAction="http://tempuri.org/IUserAuthenticationService/GetDetails_OrganizationAccountantRe" +
            "sponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.OrganizationAccountantInfo>> GetDetails_OrganizationAccountantAsync(string ID, string OrganizationCode, string AccountantCode, bool IsAudit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/Save_OrganizationAccountant", ReplyAction="http://tempuri.org/IUserAuthenticationService/Save_OrganizationAccountantResponse" +
            "")]
        iGST.Auth_Svc.Save_OrganizationAccountantResponse Save_OrganizationAccountant(iGST.Auth_Svc.Save_OrganizationAccountantRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/Save_OrganizationAccountant", ReplyAction="http://tempuri.org/IUserAuthenticationService/Save_OrganizationAccountantResponse" +
            "")]
        System.Threading.Tasks.Task<iGST.Auth_Svc.Save_OrganizationAccountantResponse> Save_OrganizationAccountantAsync(iGST.Auth_Svc.Save_OrganizationAccountantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/GetDashboard_Organization", ReplyAction="http://tempuri.org/IUserAuthenticationService/GetDashboard_OrganizationResponse")]
        System.Collections.Generic.List<BusinessObjects.OrganizationDashBoardInfo> GetDashboard_Organization(string OrganizationCode, string FromDate, string ToDate, string Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthenticationService/GetDashboard_Organization", ReplyAction="http://tempuri.org/IUserAuthenticationService/GetDashboard_OrganizationResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.OrganizationDashBoardInfo>> GetDashboard_OrganizationAsync(string OrganizationCode, string FromDate, string ToDate, string Type);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="User_Login", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class User_LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string UserType;
        
        public User_LoginRequest() {
        }
        
        public User_LoginRequest(string UserName, string Password, string UserType) {
            this.UserName = UserName;
            this.Password = Password;
            this.UserType = UserType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="User_LoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class User_LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BusinessObjects.UserInfo User_LoginResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errormsg;
        
        public User_LoginResponse() {
        }
        
        public User_LoginResponse(BusinessObjects.UserInfo User_LoginResult, string errormsg) {
            this.User_LoginResult = User_LoginResult;
            this.errormsg = errormsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="User_ChangePassword", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class User_ChangePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string OldPssword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string NewPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public BusinessObjects.UserInfo objUserInfo;
        
        public User_ChangePasswordRequest() {
        }
        
        public User_ChangePasswordRequest(string OldPssword, string NewPassword, BusinessObjects.UserInfo objUserInfo) {
            this.OldPssword = OldPssword;
            this.NewPassword = NewPassword;
            this.objUserInfo = objUserInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="User_ChangePasswordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class User_ChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool User_ChangePasswordResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errormsg;
        
        public User_ChangePasswordResponse() {
        }
        
        public User_ChangePasswordResponse(bool User_ChangePasswordResult, string errormsg) {
            this.User_ChangePasswordResult = User_ChangePasswordResult;
            this.errormsg = errormsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="User_ForgotPassword", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class User_ForgotPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserCodeEmailIDMobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string OTPValidityDuration;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string OTPSendOption;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string UserCode;
        
        public User_ForgotPasswordRequest() {
        }
        
        public User_ForgotPasswordRequest(string UserCodeEmailIDMobile, string OTPValidityDuration, string OTPSendOption, string UserCode) {
            this.UserCodeEmailIDMobile = UserCodeEmailIDMobile;
            this.OTPValidityDuration = OTPValidityDuration;
            this.OTPSendOption = OTPSendOption;
            this.UserCode = UserCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="User_ForgotPasswordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class User_ForgotPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool User_ForgotPasswordResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string OTP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string errormsg;
        
        public User_ForgotPasswordResponse() {
        }
        
        public User_ForgotPasswordResponse(bool User_ForgotPasswordResult, string OTP, string errormsg) {
            this.User_ForgotPasswordResult = User_ForgotPasswordResult;
            this.OTP = OTP;
            this.errormsg = errormsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SocialMediaLogin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SocialMediaLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string UserType;
        
        public SocialMediaLoginRequest() {
        }
        
        public SocialMediaLoginRequest(string UserName, string UserType) {
            this.UserName = UserName;
            this.UserType = UserType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SocialMediaLoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SocialMediaLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BusinessObjects.UserInfo SocialMediaLoginResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errormsg;
        
        public SocialMediaLoginResponse() {
        }
        
        public SocialMediaLoginResponse(BusinessObjects.UserInfo SocialMediaLoginResult, string errormsg) {
            this.SocialMediaLoginResult = SocialMediaLoginResult;
            this.errormsg = errormsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save_UserModerate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Save_UserModerateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool isOnlyDelete;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public BusinessObjects.UserInfo objUserInfoToBeSaved;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string UserCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string functions;
        
        public Save_UserModerateRequest() {
        }
        
        public Save_UserModerateRequest(bool isOnlyDelete, BusinessObjects.UserInfo objUserInfoToBeSaved, string UserCode, string functions) {
            this.isOnlyDelete = isOnlyDelete;
            this.objUserInfoToBeSaved = objUserInfoToBeSaved;
            this.UserCode = UserCode;
            this.functions = functions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save_UserModerateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Save_UserModerateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Save_UserModerateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errormsg;
        
        public Save_UserModerateResponse() {
        }
        
        public Save_UserModerateResponse(bool Save_UserModerateResult, string errormsg) {
            this.Save_UserModerateResult = Save_UserModerateResult;
            this.errormsg = errormsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Email_Verification", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Email_VerificationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string EmailVerifictionKey;
        
        public Email_VerificationRequest() {
        }
        
        public Email_VerificationRequest(string EmailVerifictionKey) {
            this.EmailVerifictionKey = EmailVerifictionKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Email_VerificationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Email_VerificationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Email_VerificationResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errormsg;
        
        public Email_VerificationResponse() {
        }
        
        public Email_VerificationResponse(bool Email_VerificationResult, string errormsg) {
            this.Email_VerificationResult = Email_VerificationResult;
            this.errormsg = errormsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLogin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Password;
        
        public UserLoginRequest() {
        }
        
        public UserLoginRequest(string UserID, string Password) {
            this.UserID = UserID;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UserLoginResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public BusinessObjects.UserInfo obj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ErrorCode;
        
        public UserLoginResponse() {
        }
        
        public UserLoginResponse(bool UserLoginResult, BusinessObjects.UserInfo obj, string ErrorCode) {
            this.UserLoginResult = UserLoginResult;
            this.obj = obj;
            this.ErrorCode = ErrorCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserRegistered_EmailChange", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserRegistered_EmailChangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserIdToSave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool isNeedToCheckEmailID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string EmailID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public bool isNeedToCheckPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string EmailIDTobeChanged;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string UserID;
        
        public UserRegistered_EmailChangeRequest() {
        }
        
        public UserRegistered_EmailChangeRequest(string UserIdToSave, bool isNeedToCheckEmailID, string EmailID, bool isNeedToCheckPassword, string Password, string EmailIDTobeChanged, string UserID) {
            this.UserIdToSave = UserIdToSave;
            this.isNeedToCheckEmailID = isNeedToCheckEmailID;
            this.EmailID = EmailID;
            this.isNeedToCheckPassword = isNeedToCheckPassword;
            this.Password = Password;
            this.EmailIDTobeChanged = EmailIDTobeChanged;
            this.UserID = UserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserRegistered_EmailChangeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserRegistered_EmailChangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UserRegistered_EmailChangeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errormsg;
        
        public UserRegistered_EmailChangeResponse() {
        }
        
        public UserRegistered_EmailChangeResponse(bool UserRegistered_EmailChangeResult, string errormsg) {
            this.UserRegistered_EmailChangeResult = UserRegistered_EmailChangeResult;
            this.errormsg = errormsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserRegistered_MobileChange", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserRegistered_MobileChangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserIdToSave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool isNeedToCheckMobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Mobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public bool isNeedToCheckPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string MobileTobeChanged;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string UserID;
        
        public UserRegistered_MobileChangeRequest() {
        }
        
        public UserRegistered_MobileChangeRequest(string UserIdToSave, bool isNeedToCheckMobile, string Mobile, bool isNeedToCheckPassword, string Password, string MobileTobeChanged, string UserID) {
            this.UserIdToSave = UserIdToSave;
            this.isNeedToCheckMobile = isNeedToCheckMobile;
            this.Mobile = Mobile;
            this.isNeedToCheckPassword = isNeedToCheckPassword;
            this.Password = Password;
            this.MobileTobeChanged = MobileTobeChanged;
            this.UserID = UserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserRegistered_MobileChangeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserRegistered_MobileChangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UserRegistered_MobileChangeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errormsg;
        
        public UserRegistered_MobileChangeResponse() {
        }
        
        public UserRegistered_MobileChangeResponse(bool UserRegistered_MobileChangeResult, string errormsg) {
            this.UserRegistered_MobileChangeResult = UserRegistered_MobileChangeResult;
            this.errormsg = errormsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save_Organization", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Save_OrganizationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool isOnlyDelete;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public BusinessObjects.OrganizationInfo obj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public BusinessObjects.UserInfo objUserInfo;
        
        public Save_OrganizationRequest() {
        }
        
        public Save_OrganizationRequest(bool isOnlyDelete, BusinessObjects.OrganizationInfo obj, BusinessObjects.UserInfo objUserInfo) {
            this.isOnlyDelete = isOnlyDelete;
            this.obj = obj;
            this.objUserInfo = objUserInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save_OrganizationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Save_OrganizationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Save_OrganizationResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errormsg;
        
        public Save_OrganizationResponse() {
        }
        
        public Save_OrganizationResponse(bool Save_OrganizationResult, string errormsg) {
            this.Save_OrganizationResult = Save_OrganizationResult;
            this.errormsg = errormsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save_OrganizationAccountant", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Save_OrganizationAccountantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool isOnlyDelete;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public BusinessObjects.OrganizationAccountantInfo obj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public BusinessObjects.UserInfo objUserInfo;
        
        public Save_OrganizationAccountantRequest() {
        }
        
        public Save_OrganizationAccountantRequest(bool isOnlyDelete, BusinessObjects.OrganizationAccountantInfo obj, BusinessObjects.UserInfo objUserInfo) {
            this.isOnlyDelete = isOnlyDelete;
            this.obj = obj;
            this.objUserInfo = objUserInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save_OrganizationAccountantResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Save_OrganizationAccountantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Save_OrganizationAccountantResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errormsg;
        
        public Save_OrganizationAccountantResponse() {
        }
        
        public Save_OrganizationAccountantResponse(bool Save_OrganizationAccountantResult, string errormsg) {
            this.Save_OrganizationAccountantResult = Save_OrganizationAccountantResult;
            this.errormsg = errormsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserAuthenticationServiceChannel : iGST.Auth_Svc.IUserAuthenticationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserAuthenticationServiceClient : System.ServiceModel.ClientBase<iGST.Auth_Svc.IUserAuthenticationService>, iGST.Auth_Svc.IUserAuthenticationService {
        
        public UserAuthenticationServiceClient() {
        }
        
        public UserAuthenticationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserAuthenticationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAuthenticationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAuthenticationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iGST.Auth_Svc.User_LoginResponse iGST.Auth_Svc.IUserAuthenticationService.User_Login(iGST.Auth_Svc.User_LoginRequest request) {
            return base.Channel.User_Login(request);
        }
        
        public BusinessObjects.UserInfo User_Login(string UserName, string Password, string UserType, out string errormsg) {
            iGST.Auth_Svc.User_LoginRequest inValue = new iGST.Auth_Svc.User_LoginRequest();
            inValue.UserName = UserName;
            inValue.Password = Password;
            inValue.UserType = UserType;
            iGST.Auth_Svc.User_LoginResponse retVal = ((iGST.Auth_Svc.IUserAuthenticationService)(this)).User_Login(inValue);
            errormsg = retVal.errormsg;
            return retVal.User_LoginResult;
        }
        
        public System.Threading.Tasks.Task<iGST.Auth_Svc.User_LoginResponse> User_LoginAsync(iGST.Auth_Svc.User_LoginRequest request) {
            return base.Channel.User_LoginAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iGST.Auth_Svc.User_ChangePasswordResponse iGST.Auth_Svc.IUserAuthenticationService.User_ChangePassword(iGST.Auth_Svc.User_ChangePasswordRequest request) {
            return base.Channel.User_ChangePassword(request);
        }
        
        public bool User_ChangePassword(string OldPssword, string NewPassword, BusinessObjects.UserInfo objUserInfo, out string errormsg) {
            iGST.Auth_Svc.User_ChangePasswordRequest inValue = new iGST.Auth_Svc.User_ChangePasswordRequest();
            inValue.OldPssword = OldPssword;
            inValue.NewPassword = NewPassword;
            inValue.objUserInfo = objUserInfo;
            iGST.Auth_Svc.User_ChangePasswordResponse retVal = ((iGST.Auth_Svc.IUserAuthenticationService)(this)).User_ChangePassword(inValue);
            errormsg = retVal.errormsg;
            return retVal.User_ChangePasswordResult;
        }
        
        public System.Threading.Tasks.Task<iGST.Auth_Svc.User_ChangePasswordResponse> User_ChangePasswordAsync(iGST.Auth_Svc.User_ChangePasswordRequest request) {
            return base.Channel.User_ChangePasswordAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iGST.Auth_Svc.User_ForgotPasswordResponse iGST.Auth_Svc.IUserAuthenticationService.User_ForgotPassword(iGST.Auth_Svc.User_ForgotPasswordRequest request) {
            return base.Channel.User_ForgotPassword(request);
        }
        
        public bool User_ForgotPassword(string UserCodeEmailIDMobile, string OTPValidityDuration, string OTPSendOption, string UserCode, out string OTP, out string errormsg) {
            iGST.Auth_Svc.User_ForgotPasswordRequest inValue = new iGST.Auth_Svc.User_ForgotPasswordRequest();
            inValue.UserCodeEmailIDMobile = UserCodeEmailIDMobile;
            inValue.OTPValidityDuration = OTPValidityDuration;
            inValue.OTPSendOption = OTPSendOption;
            inValue.UserCode = UserCode;
            iGST.Auth_Svc.User_ForgotPasswordResponse retVal = ((iGST.Auth_Svc.IUserAuthenticationService)(this)).User_ForgotPassword(inValue);
            OTP = retVal.OTP;
            errormsg = retVal.errormsg;
            return retVal.User_ForgotPasswordResult;
        }
        
        public System.Threading.Tasks.Task<iGST.Auth_Svc.User_ForgotPasswordResponse> User_ForgotPasswordAsync(iGST.Auth_Svc.User_ForgotPasswordRequest request) {
            return base.Channel.User_ForgotPasswordAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iGST.Auth_Svc.SocialMediaLoginResponse iGST.Auth_Svc.IUserAuthenticationService.SocialMediaLogin(iGST.Auth_Svc.SocialMediaLoginRequest request) {
            return base.Channel.SocialMediaLogin(request);
        }
        
        public BusinessObjects.UserInfo SocialMediaLogin(string UserName, string UserType, out string errormsg) {
            iGST.Auth_Svc.SocialMediaLoginRequest inValue = new iGST.Auth_Svc.SocialMediaLoginRequest();
            inValue.UserName = UserName;
            inValue.UserType = UserType;
            iGST.Auth_Svc.SocialMediaLoginResponse retVal = ((iGST.Auth_Svc.IUserAuthenticationService)(this)).SocialMediaLogin(inValue);
            errormsg = retVal.errormsg;
            return retVal.SocialMediaLoginResult;
        }
        
        public System.Threading.Tasks.Task<iGST.Auth_Svc.SocialMediaLoginResponse> SocialMediaLoginAsync(iGST.Auth_Svc.SocialMediaLoginRequest request) {
            return base.Channel.SocialMediaLoginAsync(request);
        }
        
        public System.Collections.Generic.List<BusinessObjects.UserInfo> GetList_UserModerate(string OrganizationCode, string UserCode, string UserType) {
            return base.Channel.GetList_UserModerate(OrganizationCode, UserCode, UserType);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.UserInfo>> GetList_UserModerateAsync(string OrganizationCode, string UserCode, string UserType) {
            return base.Channel.GetList_UserModerateAsync(OrganizationCode, UserCode, UserType);
        }
        
        public BusinessObjects.UserInfo GetDetails_UserModerate(string UserCode) {
            return base.Channel.GetDetails_UserModerate(UserCode);
        }
        
        public System.Threading.Tasks.Task<BusinessObjects.UserInfo> GetDetails_UserModerateAsync(string UserCode) {
            return base.Channel.GetDetails_UserModerateAsync(UserCode);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iGST.Auth_Svc.Save_UserModerateResponse iGST.Auth_Svc.IUserAuthenticationService.Save_UserModerate(iGST.Auth_Svc.Save_UserModerateRequest request) {
            return base.Channel.Save_UserModerate(request);
        }
        
        public bool Save_UserModerate(bool isOnlyDelete, BusinessObjects.UserInfo objUserInfoToBeSaved, string UserCode, string functions, out string errormsg) {
            iGST.Auth_Svc.Save_UserModerateRequest inValue = new iGST.Auth_Svc.Save_UserModerateRequest();
            inValue.isOnlyDelete = isOnlyDelete;
            inValue.objUserInfoToBeSaved = objUserInfoToBeSaved;
            inValue.UserCode = UserCode;
            inValue.functions = functions;
            iGST.Auth_Svc.Save_UserModerateResponse retVal = ((iGST.Auth_Svc.IUserAuthenticationService)(this)).Save_UserModerate(inValue);
            errormsg = retVal.errormsg;
            return retVal.Save_UserModerateResult;
        }
        
        public System.Threading.Tasks.Task<iGST.Auth_Svc.Save_UserModerateResponse> Save_UserModerateAsync(iGST.Auth_Svc.Save_UserModerateRequest request) {
            return base.Channel.Save_UserModerateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iGST.Auth_Svc.Email_VerificationResponse iGST.Auth_Svc.IUserAuthenticationService.Email_Verification(iGST.Auth_Svc.Email_VerificationRequest request) {
            return base.Channel.Email_Verification(request);
        }
        
        public bool Email_Verification(string EmailVerifictionKey, out string errormsg) {
            iGST.Auth_Svc.Email_VerificationRequest inValue = new iGST.Auth_Svc.Email_VerificationRequest();
            inValue.EmailVerifictionKey = EmailVerifictionKey;
            iGST.Auth_Svc.Email_VerificationResponse retVal = ((iGST.Auth_Svc.IUserAuthenticationService)(this)).Email_Verification(inValue);
            errormsg = retVal.errormsg;
            return retVal.Email_VerificationResult;
        }
        
        public System.Threading.Tasks.Task<iGST.Auth_Svc.Email_VerificationResponse> Email_VerificationAsync(iGST.Auth_Svc.Email_VerificationRequest request) {
            return base.Channel.Email_VerificationAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iGST.Auth_Svc.UserLoginResponse iGST.Auth_Svc.IUserAuthenticationService.UserLogin(iGST.Auth_Svc.UserLoginRequest request) {
            return base.Channel.UserLogin(request);
        }
        
        public bool UserLogin(string UserID, string Password, out BusinessObjects.UserInfo obj, out string ErrorCode) {
            iGST.Auth_Svc.UserLoginRequest inValue = new iGST.Auth_Svc.UserLoginRequest();
            inValue.UserID = UserID;
            inValue.Password = Password;
            iGST.Auth_Svc.UserLoginResponse retVal = ((iGST.Auth_Svc.IUserAuthenticationService)(this)).UserLogin(inValue);
            obj = retVal.obj;
            ErrorCode = retVal.ErrorCode;
            return retVal.UserLoginResult;
        }
        
        public System.Threading.Tasks.Task<iGST.Auth_Svc.UserLoginResponse> UserLoginAsync(iGST.Auth_Svc.UserLoginRequest request) {
            return base.Channel.UserLoginAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iGST.Auth_Svc.UserRegistered_EmailChangeResponse iGST.Auth_Svc.IUserAuthenticationService.UserRegistered_EmailChange(iGST.Auth_Svc.UserRegistered_EmailChangeRequest request) {
            return base.Channel.UserRegistered_EmailChange(request);
        }
        
        public bool UserRegistered_EmailChange(string UserIdToSave, bool isNeedToCheckEmailID, string EmailID, bool isNeedToCheckPassword, string Password, string EmailIDTobeChanged, string UserID, out string errormsg) {
            iGST.Auth_Svc.UserRegistered_EmailChangeRequest inValue = new iGST.Auth_Svc.UserRegistered_EmailChangeRequest();
            inValue.UserIdToSave = UserIdToSave;
            inValue.isNeedToCheckEmailID = isNeedToCheckEmailID;
            inValue.EmailID = EmailID;
            inValue.isNeedToCheckPassword = isNeedToCheckPassword;
            inValue.Password = Password;
            inValue.EmailIDTobeChanged = EmailIDTobeChanged;
            inValue.UserID = UserID;
            iGST.Auth_Svc.UserRegistered_EmailChangeResponse retVal = ((iGST.Auth_Svc.IUserAuthenticationService)(this)).UserRegistered_EmailChange(inValue);
            errormsg = retVal.errormsg;
            return retVal.UserRegistered_EmailChangeResult;
        }
        
        public System.Threading.Tasks.Task<iGST.Auth_Svc.UserRegistered_EmailChangeResponse> UserRegistered_EmailChangeAsync(iGST.Auth_Svc.UserRegistered_EmailChangeRequest request) {
            return base.Channel.UserRegistered_EmailChangeAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iGST.Auth_Svc.UserRegistered_MobileChangeResponse iGST.Auth_Svc.IUserAuthenticationService.UserRegistered_MobileChange(iGST.Auth_Svc.UserRegistered_MobileChangeRequest request) {
            return base.Channel.UserRegistered_MobileChange(request);
        }
        
        public bool UserRegistered_MobileChange(string UserIdToSave, bool isNeedToCheckMobile, string Mobile, bool isNeedToCheckPassword, string Password, string MobileTobeChanged, string UserID, out string errormsg) {
            iGST.Auth_Svc.UserRegistered_MobileChangeRequest inValue = new iGST.Auth_Svc.UserRegistered_MobileChangeRequest();
            inValue.UserIdToSave = UserIdToSave;
            inValue.isNeedToCheckMobile = isNeedToCheckMobile;
            inValue.Mobile = Mobile;
            inValue.isNeedToCheckPassword = isNeedToCheckPassword;
            inValue.Password = Password;
            inValue.MobileTobeChanged = MobileTobeChanged;
            inValue.UserID = UserID;
            iGST.Auth_Svc.UserRegistered_MobileChangeResponse retVal = ((iGST.Auth_Svc.IUserAuthenticationService)(this)).UserRegistered_MobileChange(inValue);
            errormsg = retVal.errormsg;
            return retVal.UserRegistered_MobileChangeResult;
        }
        
        public System.Threading.Tasks.Task<iGST.Auth_Svc.UserRegistered_MobileChangeResponse> UserRegistered_MobileChangeAsync(iGST.Auth_Svc.UserRegistered_MobileChangeRequest request) {
            return base.Channel.UserRegistered_MobileChangeAsync(request);
        }
        
        public System.Collections.Generic.List<BusinessObjects.OrganizationInfo> GetList_OrganizationDropdownList(string OrganizationCode, string isActive, string UserCode) {
            return base.Channel.GetList_OrganizationDropdownList(OrganizationCode, isActive, UserCode);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.OrganizationInfo>> GetList_OrganizationDropdownListAsync(string OrganizationCode, string isActive, string UserCode) {
            return base.Channel.GetList_OrganizationDropdownListAsync(OrganizationCode, isActive, UserCode);
        }
        
        public System.Collections.Generic.List<BusinessObjects.OrganizationInfo> GetList_Organization(string OrganizationCode, string OrganizationName, string City, string State, string Country, string UserID, bool IsActive, string LanguageId) {
            return base.Channel.GetList_Organization(OrganizationCode, OrganizationName, City, State, Country, UserID, IsActive, LanguageId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.OrganizationInfo>> GetList_OrganizationAsync(string OrganizationCode, string OrganizationName, string City, string State, string Country, string UserID, bool IsActive, string LanguageId) {
            return base.Channel.GetList_OrganizationAsync(OrganizationCode, OrganizationName, City, State, Country, UserID, IsActive, LanguageId);
        }
        
        public BusinessObjects.OrganizationInfo GetDetails_Organization(string OrganizationCode, string OrganizationName, string City, string State, string Country, string UserID, bool IsActive, bool NeedBranchList, string LanguageId) {
            return base.Channel.GetDetails_Organization(OrganizationCode, OrganizationName, City, State, Country, UserID, IsActive, NeedBranchList, LanguageId);
        }
        
        public System.Threading.Tasks.Task<BusinessObjects.OrganizationInfo> GetDetails_OrganizationAsync(string OrganizationCode, string OrganizationName, string City, string State, string Country, string UserID, bool IsActive, bool NeedBranchList, string LanguageId) {
            return base.Channel.GetDetails_OrganizationAsync(OrganizationCode, OrganizationName, City, State, Country, UserID, IsActive, NeedBranchList, LanguageId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iGST.Auth_Svc.Save_OrganizationResponse iGST.Auth_Svc.IUserAuthenticationService.Save_Organization(iGST.Auth_Svc.Save_OrganizationRequest request) {
            return base.Channel.Save_Organization(request);
        }
        
        public bool Save_Organization(bool isOnlyDelete, BusinessObjects.OrganizationInfo obj, BusinessObjects.UserInfo objUserInfo, out string errormsg) {
            iGST.Auth_Svc.Save_OrganizationRequest inValue = new iGST.Auth_Svc.Save_OrganizationRequest();
            inValue.isOnlyDelete = isOnlyDelete;
            inValue.obj = obj;
            inValue.objUserInfo = objUserInfo;
            iGST.Auth_Svc.Save_OrganizationResponse retVal = ((iGST.Auth_Svc.IUserAuthenticationService)(this)).Save_Organization(inValue);
            errormsg = retVal.errormsg;
            return retVal.Save_OrganizationResult;
        }
        
        public System.Threading.Tasks.Task<iGST.Auth_Svc.Save_OrganizationResponse> Save_OrganizationAsync(iGST.Auth_Svc.Save_OrganizationRequest request) {
            return base.Channel.Save_OrganizationAsync(request);
        }
        
        public System.Collections.Generic.List<BusinessObjects.OrganizationAccountantInfo> GetList_OrganizationAccountant(string ID, string OrganizationCode, string AccountantCode, bool IsAudit) {
            return base.Channel.GetList_OrganizationAccountant(ID, OrganizationCode, AccountantCode, IsAudit);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.OrganizationAccountantInfo>> GetList_OrganizationAccountantAsync(string ID, string OrganizationCode, string AccountantCode, bool IsAudit) {
            return base.Channel.GetList_OrganizationAccountantAsync(ID, OrganizationCode, AccountantCode, IsAudit);
        }
        
        public System.Collections.Generic.List<BusinessObjects.OrganizationAccountantInfo> GetDetails_OrganizationAccountant(string ID, string OrganizationCode, string AccountantCode, bool IsAudit) {
            return base.Channel.GetDetails_OrganizationAccountant(ID, OrganizationCode, AccountantCode, IsAudit);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.OrganizationAccountantInfo>> GetDetails_OrganizationAccountantAsync(string ID, string OrganizationCode, string AccountantCode, bool IsAudit) {
            return base.Channel.GetDetails_OrganizationAccountantAsync(ID, OrganizationCode, AccountantCode, IsAudit);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iGST.Auth_Svc.Save_OrganizationAccountantResponse iGST.Auth_Svc.IUserAuthenticationService.Save_OrganizationAccountant(iGST.Auth_Svc.Save_OrganizationAccountantRequest request) {
            return base.Channel.Save_OrganizationAccountant(request);
        }
        
        public bool Save_OrganizationAccountant(bool isOnlyDelete, BusinessObjects.OrganizationAccountantInfo obj, BusinessObjects.UserInfo objUserInfo, out string errormsg) {
            iGST.Auth_Svc.Save_OrganizationAccountantRequest inValue = new iGST.Auth_Svc.Save_OrganizationAccountantRequest();
            inValue.isOnlyDelete = isOnlyDelete;
            inValue.obj = obj;
            inValue.objUserInfo = objUserInfo;
            iGST.Auth_Svc.Save_OrganizationAccountantResponse retVal = ((iGST.Auth_Svc.IUserAuthenticationService)(this)).Save_OrganizationAccountant(inValue);
            errormsg = retVal.errormsg;
            return retVal.Save_OrganizationAccountantResult;
        }
        
        public System.Threading.Tasks.Task<iGST.Auth_Svc.Save_OrganizationAccountantResponse> Save_OrganizationAccountantAsync(iGST.Auth_Svc.Save_OrganizationAccountantRequest request) {
            return base.Channel.Save_OrganizationAccountantAsync(request);
        }
        
        public System.Collections.Generic.List<BusinessObjects.OrganizationDashBoardInfo> GetDashboard_Organization(string OrganizationCode, string FromDate, string ToDate, string Type) {
            return base.Channel.GetDashboard_Organization(OrganizationCode, FromDate, ToDate, Type);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.OrganizationDashBoardInfo>> GetDashboard_OrganizationAsync(string OrganizationCode, string FromDate, string ToDate, string Type) {
            return base.Channel.GetDashboard_OrganizationAsync(OrganizationCode, FromDate, ToDate, Type);
        }
    }
}
