//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGST.Product_Svc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Product_Svc.IProductService")]
    public interface IProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetList_ProductDropdownlist", ReplyAction="http://tempuri.org/IProductService/GetList_ProductDropdownlistResponse")]
        System.Collections.Generic.List<BusinessObjects.ProductInfo> GetList_ProductDropdownlist(string ProductID, string ProductName, bool IsExpense, string OrganizationCode, string CategoryId, bool IsActive, string LanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetList_ProductDropdownlist", ReplyAction="http://tempuri.org/IProductService/GetList_ProductDropdownlistResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.ProductInfo>> GetList_ProductDropdownlistAsync(string ProductID, string ProductName, bool IsExpense, string OrganizationCode, string CategoryId, bool IsActive, string LanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetList_Product", ReplyAction="http://tempuri.org/IProductService/GetList_ProductResponse")]
        System.Collections.Generic.List<BusinessObjects.ProductInfo> GetList_Product(string ProductID, string ProductName, string IsExpense, string OrganizationCode, string CategoryId, bool IsActive, string LanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetList_Product", ReplyAction="http://tempuri.org/IProductService/GetList_ProductResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.ProductInfo>> GetList_ProductAsync(string ProductID, string ProductName, string IsExpense, string OrganizationCode, string CategoryId, bool IsActive, string LanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetDetails_Product", ReplyAction="http://tempuri.org/IProductService/GetDetails_ProductResponse")]
        BusinessObjects.ProductInfo GetDetails_Product(string ProductID, string ProductName, string IsExpense, string OrganizationCode, string CategoryId, bool IsActive, string LanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetDetails_Product", ReplyAction="http://tempuri.org/IProductService/GetDetails_ProductResponse")]
        System.Threading.Tasks.Task<BusinessObjects.ProductInfo> GetDetails_ProductAsync(string ProductID, string ProductName, string IsExpense, string OrganizationCode, string CategoryId, bool IsActive, string LanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Save_Product", ReplyAction="http://tempuri.org/IProductService/Save_ProductResponse")]
        iGST.Product_Svc.Save_ProductResponse Save_Product(iGST.Product_Svc.Save_ProductRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Save_Product", ReplyAction="http://tempuri.org/IProductService/Save_ProductResponse")]
        System.Threading.Tasks.Task<iGST.Product_Svc.Save_ProductResponse> Save_ProductAsync(iGST.Product_Svc.Save_ProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Upload_Product", ReplyAction="http://tempuri.org/IProductService/Upload_ProductResponse")]
        iGST.Product_Svc.Upload_ProductResponse Upload_Product(iGST.Product_Svc.Upload_ProductRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Upload_Product", ReplyAction="http://tempuri.org/IProductService/Upload_ProductResponse")]
        System.Threading.Tasks.Task<iGST.Product_Svc.Upload_ProductResponse> Upload_ProductAsync(iGST.Product_Svc.Upload_ProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetList_ProductOrganization", ReplyAction="http://tempuri.org/IProductService/GetList_ProductOrganizationResponse")]
        System.Collections.Generic.List<BusinessObjects.ProductOrganiztionInfo> GetList_ProductOrganization(string OrganizationproductId, string ProductID, string ProductName, string OrganizationCode, string CountryId, bool IsActive, string LanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetList_ProductOrganization", ReplyAction="http://tempuri.org/IProductService/GetList_ProductOrganizationResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.ProductOrganiztionInfo>> GetList_ProductOrganizationAsync(string OrganizationproductId, string ProductID, string ProductName, string OrganizationCode, string CountryId, bool IsActive, string LanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetDetails_ProductOrganization", ReplyAction="http://tempuri.org/IProductService/GetDetails_ProductOrganizationResponse")]
        System.Collections.Generic.List<BusinessObjects.ProductOrganiztionInfo> GetDetails_ProductOrganization(string OrganizationproductId, string ProductID, string ProductName, string OrganizationCode, string CountryId, bool IsActive, string LanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetDetails_ProductOrganization", ReplyAction="http://tempuri.org/IProductService/GetDetails_ProductOrganizationResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.ProductOrganiztionInfo>> GetDetails_ProductOrganizationAsync(string OrganizationproductId, string ProductID, string ProductName, string OrganizationCode, string CountryId, bool IsActive, string LanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Save_ProductOrganization", ReplyAction="http://tempuri.org/IProductService/Save_ProductOrganizationResponse")]
        iGST.Product_Svc.Save_ProductOrganizationResponse Save_ProductOrganization(iGST.Product_Svc.Save_ProductOrganizationRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Save_ProductOrganization", ReplyAction="http://tempuri.org/IProductService/Save_ProductOrganizationResponse")]
        System.Threading.Tasks.Task<iGST.Product_Svc.Save_ProductOrganizationResponse> Save_ProductOrganizationAsync(iGST.Product_Svc.Save_ProductOrganizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Save_ProductOrganizationImage", ReplyAction="http://tempuri.org/IProductService/Save_ProductOrganizationImageResponse")]
        iGST.Product_Svc.Save_ProductOrganizationImageResponse Save_ProductOrganizationImage(iGST.Product_Svc.Save_ProductOrganizationImageRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Save_ProductOrganizationImage", ReplyAction="http://tempuri.org/IProductService/Save_ProductOrganizationImageResponse")]
        System.Threading.Tasks.Task<iGST.Product_Svc.Save_ProductOrganizationImageResponse> Save_ProductOrganizationImageAsync(iGST.Product_Svc.Save_ProductOrganizationImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetList_ProductOrganizationImage", ReplyAction="http://tempuri.org/IProductService/GetList_ProductOrganizationImageResponse")]
        System.Collections.Generic.List<BusinessObjects.ProductOrganiztionImageInfo> GetList_ProductOrganizationImage(string ImageId, string OrganizationproductId, string ProductID, string IsActive, string IsMain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetList_ProductOrganizationImage", ReplyAction="http://tempuri.org/IProductService/GetList_ProductOrganizationImageResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.ProductOrganiztionImageInfo>> GetList_ProductOrganizationImageAsync(string ImageId, string OrganizationproductId, string ProductID, string IsActive, string IsMain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetDetails_ProductOrganizationImage", ReplyAction="http://tempuri.org/IProductService/GetDetails_ProductOrganizationImageResponse")]
        BusinessObjects.ProductOrganiztionImageInfo GetDetails_ProductOrganizationImage(string ImageId, string OrganizationproductId, string ProductID, string IsActive, string IsMain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetDetails_ProductOrganizationImage", ReplyAction="http://tempuri.org/IProductService/GetDetails_ProductOrganizationImageResponse")]
        System.Threading.Tasks.Task<BusinessObjects.ProductOrganiztionImageInfo> GetDetails_ProductOrganizationImageAsync(string ImageId, string OrganizationproductId, string ProductID, string IsActive, string IsMain);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save_Product", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Save_ProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool isOnlyDelete;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public BusinessObjects.ProductInfo obj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public BusinessObjects.UserInfo objUserInfo;
        
        public Save_ProductRequest() {
        }
        
        public Save_ProductRequest(bool isOnlyDelete, BusinessObjects.ProductInfo obj, BusinessObjects.UserInfo objUserInfo) {
            this.isOnlyDelete = isOnlyDelete;
            this.obj = obj;
            this.objUserInfo = objUserInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save_ProductResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Save_ProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Save_ProductResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errormsg;
        
        public Save_ProductResponse() {
        }
        
        public Save_ProductResponse(bool Save_ProductResult, string errormsg) {
            this.Save_ProductResult = Save_ProductResult;
            this.errormsg = errormsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Upload_Product", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Upload_ProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool isOvereWrite;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataSet ds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public BusinessObjects.UserInfo objUserInfo;
        
        public Upload_ProductRequest() {
        }
        
        public Upload_ProductRequest(bool isOvereWrite, System.Data.DataSet ds, BusinessObjects.UserInfo objUserInfo) {
            this.isOvereWrite = isOvereWrite;
            this.ds = ds;
            this.objUserInfo = objUserInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Upload_ProductResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Upload_ProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Upload_ProductResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool bReturn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string errormsg;
        
        public Upload_ProductResponse() {
        }
        
        public Upload_ProductResponse(bool Upload_ProductResult, bool bReturn, string errormsg) {
            this.Upload_ProductResult = Upload_ProductResult;
            this.bReturn = bReturn;
            this.errormsg = errormsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save_ProductOrganization", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Save_ProductOrganizationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool isOnlyDelete;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public BusinessObjects.ProductOrganiztionInfo obj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public BusinessObjects.UserInfo objUserInfo;
        
        public Save_ProductOrganizationRequest() {
        }
        
        public Save_ProductOrganizationRequest(bool isOnlyDelete, BusinessObjects.ProductOrganiztionInfo obj, BusinessObjects.UserInfo objUserInfo) {
            this.isOnlyDelete = isOnlyDelete;
            this.obj = obj;
            this.objUserInfo = objUserInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save_ProductOrganizationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Save_ProductOrganizationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Save_ProductOrganizationResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errormsg;
        
        public Save_ProductOrganizationResponse() {
        }
        
        public Save_ProductOrganizationResponse(bool Save_ProductOrganizationResult, string errormsg) {
            this.Save_ProductOrganizationResult = Save_ProductOrganizationResult;
            this.errormsg = errormsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save_ProductOrganizationImage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Save_ProductOrganizationImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool isOnlyDelete;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public BusinessObjects.ProductOrganiztionImageInfo obj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public BusinessObjects.UserInfo objUserInfo;
        
        public Save_ProductOrganizationImageRequest() {
        }
        
        public Save_ProductOrganizationImageRequest(bool isOnlyDelete, BusinessObjects.ProductOrganiztionImageInfo obj, BusinessObjects.UserInfo objUserInfo) {
            this.isOnlyDelete = isOnlyDelete;
            this.obj = obj;
            this.objUserInfo = objUserInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save_ProductOrganizationImageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Save_ProductOrganizationImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Save_ProductOrganizationImageResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errormsg;
        
        public Save_ProductOrganizationImageResponse() {
        }
        
        public Save_ProductOrganizationImageResponse(bool Save_ProductOrganizationImageResult, string errormsg) {
            this.Save_ProductOrganizationImageResult = Save_ProductOrganizationImageResult;
            this.errormsg = errormsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductServiceChannel : iGST.Product_Svc.IProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<iGST.Product_Svc.IProductService>, iGST.Product_Svc.IProductService {
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<BusinessObjects.ProductInfo> GetList_ProductDropdownlist(string ProductID, string ProductName, bool IsExpense, string OrganizationCode, string CategoryId, bool IsActive, string LanguageId) {
            return base.Channel.GetList_ProductDropdownlist(ProductID, ProductName, IsExpense, OrganizationCode, CategoryId, IsActive, LanguageId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.ProductInfo>> GetList_ProductDropdownlistAsync(string ProductID, string ProductName, bool IsExpense, string OrganizationCode, string CategoryId, bool IsActive, string LanguageId) {
            return base.Channel.GetList_ProductDropdownlistAsync(ProductID, ProductName, IsExpense, OrganizationCode, CategoryId, IsActive, LanguageId);
        }
        
        public System.Collections.Generic.List<BusinessObjects.ProductInfo> GetList_Product(string ProductID, string ProductName, string IsExpense, string OrganizationCode, string CategoryId, bool IsActive, string LanguageId) {
            return base.Channel.GetList_Product(ProductID, ProductName, IsExpense, OrganizationCode, CategoryId, IsActive, LanguageId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.ProductInfo>> GetList_ProductAsync(string ProductID, string ProductName, string IsExpense, string OrganizationCode, string CategoryId, bool IsActive, string LanguageId) {
            return base.Channel.GetList_ProductAsync(ProductID, ProductName, IsExpense, OrganizationCode, CategoryId, IsActive, LanguageId);
        }
        
        public BusinessObjects.ProductInfo GetDetails_Product(string ProductID, string ProductName, string IsExpense, string OrganizationCode, string CategoryId, bool IsActive, string LanguageId) {
            return base.Channel.GetDetails_Product(ProductID, ProductName, IsExpense, OrganizationCode, CategoryId, IsActive, LanguageId);
        }
        
        public System.Threading.Tasks.Task<BusinessObjects.ProductInfo> GetDetails_ProductAsync(string ProductID, string ProductName, string IsExpense, string OrganizationCode, string CategoryId, bool IsActive, string LanguageId) {
            return base.Channel.GetDetails_ProductAsync(ProductID, ProductName, IsExpense, OrganizationCode, CategoryId, IsActive, LanguageId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iGST.Product_Svc.Save_ProductResponse iGST.Product_Svc.IProductService.Save_Product(iGST.Product_Svc.Save_ProductRequest request) {
            return base.Channel.Save_Product(request);
        }
        
        public bool Save_Product(bool isOnlyDelete, BusinessObjects.ProductInfo obj, BusinessObjects.UserInfo objUserInfo, out string errormsg) {
            iGST.Product_Svc.Save_ProductRequest inValue = new iGST.Product_Svc.Save_ProductRequest();
            inValue.isOnlyDelete = isOnlyDelete;
            inValue.obj = obj;
            inValue.objUserInfo = objUserInfo;
            iGST.Product_Svc.Save_ProductResponse retVal = ((iGST.Product_Svc.IProductService)(this)).Save_Product(inValue);
            errormsg = retVal.errormsg;
            return retVal.Save_ProductResult;
        }
        
        public System.Threading.Tasks.Task<iGST.Product_Svc.Save_ProductResponse> Save_ProductAsync(iGST.Product_Svc.Save_ProductRequest request) {
            return base.Channel.Save_ProductAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iGST.Product_Svc.Upload_ProductResponse iGST.Product_Svc.IProductService.Upload_Product(iGST.Product_Svc.Upload_ProductRequest request) {
            return base.Channel.Upload_Product(request);
        }
        
        public bool Upload_Product(bool isOvereWrite, System.Data.DataSet ds, BusinessObjects.UserInfo objUserInfo, out bool bReturn, out string errormsg) {
            iGST.Product_Svc.Upload_ProductRequest inValue = new iGST.Product_Svc.Upload_ProductRequest();
            inValue.isOvereWrite = isOvereWrite;
            inValue.ds = ds;
            inValue.objUserInfo = objUserInfo;
            iGST.Product_Svc.Upload_ProductResponse retVal = ((iGST.Product_Svc.IProductService)(this)).Upload_Product(inValue);
            bReturn = retVal.bReturn;
            errormsg = retVal.errormsg;
            return retVal.Upload_ProductResult;
        }
        
        public System.Threading.Tasks.Task<iGST.Product_Svc.Upload_ProductResponse> Upload_ProductAsync(iGST.Product_Svc.Upload_ProductRequest request) {
            return base.Channel.Upload_ProductAsync(request);
        }
        
        public System.Collections.Generic.List<BusinessObjects.ProductOrganiztionInfo> GetList_ProductOrganization(string OrganizationproductId, string ProductID, string ProductName, string OrganizationCode, string CountryId, bool IsActive, string LanguageId) {
            return base.Channel.GetList_ProductOrganization(OrganizationproductId, ProductID, ProductName, OrganizationCode, CountryId, IsActive, LanguageId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.ProductOrganiztionInfo>> GetList_ProductOrganizationAsync(string OrganizationproductId, string ProductID, string ProductName, string OrganizationCode, string CountryId, bool IsActive, string LanguageId) {
            return base.Channel.GetList_ProductOrganizationAsync(OrganizationproductId, ProductID, ProductName, OrganizationCode, CountryId, IsActive, LanguageId);
        }
        
        public System.Collections.Generic.List<BusinessObjects.ProductOrganiztionInfo> GetDetails_ProductOrganization(string OrganizationproductId, string ProductID, string ProductName, string OrganizationCode, string CountryId, bool IsActive, string LanguageId) {
            return base.Channel.GetDetails_ProductOrganization(OrganizationproductId, ProductID, ProductName, OrganizationCode, CountryId, IsActive, LanguageId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.ProductOrganiztionInfo>> GetDetails_ProductOrganizationAsync(string OrganizationproductId, string ProductID, string ProductName, string OrganizationCode, string CountryId, bool IsActive, string LanguageId) {
            return base.Channel.GetDetails_ProductOrganizationAsync(OrganizationproductId, ProductID, ProductName, OrganizationCode, CountryId, IsActive, LanguageId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iGST.Product_Svc.Save_ProductOrganizationResponse iGST.Product_Svc.IProductService.Save_ProductOrganization(iGST.Product_Svc.Save_ProductOrganizationRequest request) {
            return base.Channel.Save_ProductOrganization(request);
        }
        
        public bool Save_ProductOrganization(bool isOnlyDelete, BusinessObjects.ProductOrganiztionInfo obj, BusinessObjects.UserInfo objUserInfo, out string errormsg) {
            iGST.Product_Svc.Save_ProductOrganizationRequest inValue = new iGST.Product_Svc.Save_ProductOrganizationRequest();
            inValue.isOnlyDelete = isOnlyDelete;
            inValue.obj = obj;
            inValue.objUserInfo = objUserInfo;
            iGST.Product_Svc.Save_ProductOrganizationResponse retVal = ((iGST.Product_Svc.IProductService)(this)).Save_ProductOrganization(inValue);
            errormsg = retVal.errormsg;
            return retVal.Save_ProductOrganizationResult;
        }
        
        public System.Threading.Tasks.Task<iGST.Product_Svc.Save_ProductOrganizationResponse> Save_ProductOrganizationAsync(iGST.Product_Svc.Save_ProductOrganizationRequest request) {
            return base.Channel.Save_ProductOrganizationAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iGST.Product_Svc.Save_ProductOrganizationImageResponse iGST.Product_Svc.IProductService.Save_ProductOrganizationImage(iGST.Product_Svc.Save_ProductOrganizationImageRequest request) {
            return base.Channel.Save_ProductOrganizationImage(request);
        }
        
        public bool Save_ProductOrganizationImage(bool isOnlyDelete, BusinessObjects.ProductOrganiztionImageInfo obj, BusinessObjects.UserInfo objUserInfo, out string errormsg) {
            iGST.Product_Svc.Save_ProductOrganizationImageRequest inValue = new iGST.Product_Svc.Save_ProductOrganizationImageRequest();
            inValue.isOnlyDelete = isOnlyDelete;
            inValue.obj = obj;
            inValue.objUserInfo = objUserInfo;
            iGST.Product_Svc.Save_ProductOrganizationImageResponse retVal = ((iGST.Product_Svc.IProductService)(this)).Save_ProductOrganizationImage(inValue);
            errormsg = retVal.errormsg;
            return retVal.Save_ProductOrganizationImageResult;
        }
        
        public System.Threading.Tasks.Task<iGST.Product_Svc.Save_ProductOrganizationImageResponse> Save_ProductOrganizationImageAsync(iGST.Product_Svc.Save_ProductOrganizationImageRequest request) {
            return base.Channel.Save_ProductOrganizationImageAsync(request);
        }
        
        public System.Collections.Generic.List<BusinessObjects.ProductOrganiztionImageInfo> GetList_ProductOrganizationImage(string ImageId, string OrganizationproductId, string ProductID, string IsActive, string IsMain) {
            return base.Channel.GetList_ProductOrganizationImage(ImageId, OrganizationproductId, ProductID, IsActive, IsMain);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BusinessObjects.ProductOrganiztionImageInfo>> GetList_ProductOrganizationImageAsync(string ImageId, string OrganizationproductId, string ProductID, string IsActive, string IsMain) {
            return base.Channel.GetList_ProductOrganizationImageAsync(ImageId, OrganizationproductId, ProductID, IsActive, IsMain);
        }
        
        public BusinessObjects.ProductOrganiztionImageInfo GetDetails_ProductOrganizationImage(string ImageId, string OrganizationproductId, string ProductID, string IsActive, string IsMain) {
            return base.Channel.GetDetails_ProductOrganizationImage(ImageId, OrganizationproductId, ProductID, IsActive, IsMain);
        }
        
        public System.Threading.Tasks.Task<BusinessObjects.ProductOrganiztionImageInfo> GetDetails_ProductOrganizationImageAsync(string ImageId, string OrganizationproductId, string ProductID, string IsActive, string IsMain) {
            return base.Channel.GetDetails_ProductOrganizationImageAsync(ImageId, OrganizationproductId, ProductID, IsActive, IsMain);
        }
    }
}
